# Generated by Django 2.1.3 on 2018-12-06 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('abstract', models.CharField(max_length=512)),
                ('due_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_name', models.CharField(max_length=256)),
                ('teacher_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=512)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=512)),
                ('created', models.DateTimeField()),
                ('homework_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yang_core.Homework')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='UserHomework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField()),
                ('homework_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yang_core.Homework')),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yang_core.User')),
            ],
        ),
        migrations.AddField(
            model_name='thread',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yang_core.User'),
        ),
        migrations.AddField(
            model_name='reply',
            name='thread_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yang_core.Thread'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yang_core.User'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lecture_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yang_core.Lecture'),
        ),
    ]
