# Generated by Django 2.1.3 on 2019-02-09 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yang_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('teacher', models.CharField(max_length=256)),
                ('semester', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('day', models.CharField(max_length=256)),
                ('period', models.IntegerField()),
                ('faculty', models.CharField(max_length=256)),
                ('department', models.CharField(max_length=256)),
                ('credit', models.IntegerField()),
            ],
        ),
    ]
