# Generated by Django 2.1.3 on 2018-11-27 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yang_core', '0002_auto_20181127_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yang_core.Lecture'),
        ),
    ]
