# Generated by Django 2.1.3 on 2019-02-09 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yang_core', '0002_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='lecture',
            name='day',
            field=models.CharField(choices=[('月', '月'), ('火', '火'), ('水', '水'), ('木', '木'), ('金', '金'), ('土', '土'), ('集中', '集中'), ('その他', 'その他')], max_length=256),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (6, 6), (7, 7), (8, 8)], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='semester',
            field=models.CharField(choices=[('前学期', '前学期'), ('後学期', '後学期')], max_length=3),
        ),
        migrations.AddField(
            model_name='homework',
            name='lecture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='yang_core.Lecture'),
        ),
    ]
