# Generated by Django 2.1.3 on 2019-02-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yang_core', '0003_auto_20190209_1239'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homework',
            old_name='lecture',
            new_name='lecture_id',
        ),
    ]
