# Generated by Django 2.1.3 on 2019-02-09 13:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yang_core', '0004_auto_20190209_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='abstract',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lecture',
            name='period',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (6, 6), (7, 7), (8, 8)], null=True),
        ),
    ]
