# Generated by Django 2.1.3 on 2018-11-28 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yang_core', '0004_auto_20181128_0824'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_Homework',
            new_name='UserHomework',
        ),
    ]
