# Generated by Django 2.1.3 on 2019-02-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yang_core', '0005_auto_20190209_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='title',
            field=models.CharField(default='Homework', max_length=256),
        ),
    ]
