# Generated by Django 2.1.3 on 2019-02-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yang_core', '0009_userhomework'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=1024)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('message', models.CharField(max_length=1024)),
                ('created', models.DateTimeField()),
                ('homework_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yang_core.Homework')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yang_core.User')),
            ],
        ),
        migrations.AddField(
            model_name='reply',
            name='thread_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yang_core.Thread'),
        ),
        migrations.AddField(
            model_name='reply',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yang_core.User'),
        ),
    ]
